# Generated by Django 5.2.4 on 2026-06-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_case_created_by_alter_case_updated_by_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='core.user'),
        ),
    ]
