# Generated by Django 5.2.4 on 2025-12-03 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('updated_by', models.TextField()),
                ('updated_on', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_name', models.TextField()),
                ('methodology', models.TextField()),
                ('case_code', models.TextField()),
                ('requested_by', models.TextField()),
                ('case_manager', models.TextField()),
                ('nps_contact', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('product_type', models.TextField(blank=True, null=True)),
                ('category', models.TextField()),
                ('tags', models.JSONField(default=dict)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('tenant_id', models.UUIDField()),
            ],
            options={
                'db_table': 'core.cases',
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.TextField()),
                ('tags', models.JSONField(default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core.user_assignments',
                'unique_together': {('case', 'user')},
            },
        ),
    ]
