# Generated by Django 5.2.4 on 2025-12-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='cases',
        ),
        migrations.AlterModelTable(
            name='userassignment',
            table='user_assignments',
        ),
    ]
