# Generated by Django 5.2.4 on 2025-12-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
