# Generated by Django 5.2.4 on 2025-12-01 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('role_name', models.TextField()),
                ('permissions', models.JSONField(default=dict)),
                ('is_super_user', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('designation', models.TextField(blank=True, null=True)),
                ('tenant_id', models.UUIDField()),
                ('company', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('invalid_attempts', models.IntegerField(default=0)),
                ('tfa_secret', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('password_created_on', models.DateTimeField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=dict)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Security_api.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
