/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedCasesIndexRouteImport } from './routes/_authed/cases/index'
import { Route as AuthedCasesNewRouteImport } from './routes/_authed/cases/new'
import { Route as AuthedCasesCaseIdIndexRouteImport } from './routes/_authed/cases/$caseId/index'
import { Route as AuthedCasesCaseIdEditRouteImport } from './routes/_authed/cases/$caseId/edit'
import { Route as AuthedCasesCaseIdPartitionsNewRouteImport } from './routes/_authed/cases/$caseId/partitions/new'
import { Route as AuthedCasesCaseIdPartitionsPartitionIdRouteImport } from './routes/_authed/cases/$caseId/partitions/$partitionId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCasesIndexRoute = AuthedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCasesNewRoute = AuthedCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCasesCaseIdIndexRoute = AuthedCasesCaseIdIndexRouteImport.update({
  id: '/cases/$caseId/',
  path: '/cases/$caseId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCasesCaseIdEditRoute = AuthedCasesCaseIdEditRouteImport.update({
  id: '/cases/$caseId/edit',
  path: '/cases/$caseId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCasesCaseIdPartitionsNewRoute =
  AuthedCasesCaseIdPartitionsNewRouteImport.update({
    id: '/cases/$caseId/partitions/new',
    path: '/cases/$caseId/partitions/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCasesCaseIdPartitionsPartitionIdRoute =
  AuthedCasesCaseIdPartitionsPartitionIdRouteImport.update({
    id: '/cases/$caseId/partitions/$partitionId',
    path: '/cases/$caseId/partitions/$partitionId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/cases/new': typeof AuthedCasesNewRoute
  '/cases/': typeof AuthedCasesIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/cases/$caseId/edit': typeof AuthedCasesCaseIdEditRoute
  '/cases/$caseId/': typeof AuthedCasesCaseIdIndexRoute
  '/cases/$caseId/partitions/$partitionId': typeof AuthedCasesCaseIdPartitionsPartitionIdRoute
  '/cases/$caseId/partitions/new': typeof AuthedCasesCaseIdPartitionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/test': typeof TestIndexRoute
  '/cases/new': typeof AuthedCasesNewRoute
  '/cases': typeof AuthedCasesIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/cases/$caseId/edit': typeof AuthedCasesCaseIdEditRoute
  '/cases/$caseId': typeof AuthedCasesCaseIdIndexRoute
  '/cases/$caseId/partitions/$partitionId': typeof AuthedCasesCaseIdPartitionsPartitionIdRoute
  '/cases/$caseId/partitions/new': typeof AuthedCasesCaseIdPartitionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/_authed/cases/new': typeof AuthedCasesNewRoute
  '/_authed/cases/': typeof AuthedCasesIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/cases/$caseId/edit': typeof AuthedCasesCaseIdEditRoute
  '/_authed/cases/$caseId/': typeof AuthedCasesCaseIdIndexRoute
  '/_authed/cases/$caseId/partitions/$partitionId': typeof AuthedCasesCaseIdPartitionsPartitionIdRoute
  '/_authed/cases/$caseId/partitions/new': typeof AuthedCasesCaseIdPartitionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/'
    | '/login/'
    | '/test/'
    | '/cases/new'
    | '/cases/'
    | '/dashboard/'
    | '/profile/'
    | '/cases/$caseId/edit'
    | '/cases/$caseId/'
    | '/cases/$caseId/partitions/$partitionId'
    | '/cases/$caseId/partitions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/test'
    | '/cases/new'
    | '/cases'
    | '/dashboard'
    | '/profile'
    | '/cases/$caseId/edit'
    | '/cases/$caseId'
    | '/cases/$caseId/partitions/$partitionId'
    | '/cases/$caseId/partitions/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/home/'
    | '/login/'
    | '/test/'
    | '/_authed/cases/new'
    | '/_authed/cases/'
    | '/_authed/dashboard/'
    | '/_authed/profile/'
    | '/_authed/cases/$caseId/edit'
    | '/_authed/cases/$caseId/'
    | '/_authed/cases/$caseId/partitions/$partitionId'
    | '/_authed/cases/$caseId/partitions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/': {
      id: '/_authed/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthedCasesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/new': {
      id: '/_authed/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthedCasesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/$caseId/': {
      id: '/_authed/cases/$caseId/'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof AuthedCasesCaseIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/$caseId/edit': {
      id: '/_authed/cases/$caseId/edit'
      path: '/cases/$caseId/edit'
      fullPath: '/cases/$caseId/edit'
      preLoaderRoute: typeof AuthedCasesCaseIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/$caseId/partitions/new': {
      id: '/_authed/cases/$caseId/partitions/new'
      path: '/cases/$caseId/partitions/new'
      fullPath: '/cases/$caseId/partitions/new'
      preLoaderRoute: typeof AuthedCasesCaseIdPartitionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cases/$caseId/partitions/$partitionId': {
      id: '/_authed/cases/$caseId/partitions/$partitionId'
      path: '/cases/$caseId/partitions/$partitionId'
      fullPath: '/cases/$caseId/partitions/$partitionId'
      preLoaderRoute: typeof AuthedCasesCaseIdPartitionsPartitionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCasesNewRoute: typeof AuthedCasesNewRoute
  AuthedCasesIndexRoute: typeof AuthedCasesIndexRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedCasesCaseIdEditRoute: typeof AuthedCasesCaseIdEditRoute
  AuthedCasesCaseIdIndexRoute: typeof AuthedCasesCaseIdIndexRoute
  AuthedCasesCaseIdPartitionsPartitionIdRoute: typeof AuthedCasesCaseIdPartitionsPartitionIdRoute
  AuthedCasesCaseIdPartitionsNewRoute: typeof AuthedCasesCaseIdPartitionsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCasesNewRoute: AuthedCasesNewRoute,
  AuthedCasesIndexRoute: AuthedCasesIndexRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedCasesCaseIdEditRoute: AuthedCasesCaseIdEditRoute,
  AuthedCasesCaseIdIndexRoute: AuthedCasesCaseIdIndexRoute,
  AuthedCasesCaseIdPartitionsPartitionIdRoute:
    AuthedCasesCaseIdPartitionsPartitionIdRoute,
  AuthedCasesCaseIdPartitionsNewRoute: AuthedCasesCaseIdPartitionsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
