# Generated by Django 5.2.4 on 2025-12-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_case_table_alter_userassignment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userassignment',
            options={'managed': False},
        ),
    ]
