# Generated by Django 5.2.4 on 2025-12-08 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_case_options_alter_userassignment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_type', models.TextField()),
                ('version', models.IntegerField()),
                ('file_name', models.TextField()),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('blob_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Processing')),
                ('tags', models.JSONField(default=dict)),
                ('is_selected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"core"."dataset_metadata"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partitions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('partition_name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('step_status', models.TextField()),
                ('tags', models.JSONField(default=dict)),
            ],
            options={
                'db_table': '"core"."partitions"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='case',
            table='"core"."cases"',
        ),
        migrations.AlterModelTable(
            name='userassignment',
            table='"core"."user_assignments"',
        ),
    ]
