"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dotenv
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured

dotenv.load_dotenv()


def env_int(name, default):
    value = os.getenv(name)
    if value in (None, ""):
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("ENVIRONMENT") == "development"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    "security",
    "corsheaders",
    "rest_framework",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
]

# --- Microsoft EntraID (Azure AD) ---

ENTRA_AUDIENCE = os.getenv("ENTRA_AUDIENCE")
ENTRA_TENANT_ID = os.getenv("ENTRA_TENANT_ID")
ENTRA_CLIENT_ID = os.getenv("ENTRA_CLIENT_ID")
ENTRA_CLIENT_SECRET = os.getenv("ENTRA_CLIENT_SECRET")

ENTRA_V1_ISSUER = f"https://sts.windows.net/{ENTRA_TENANT_ID}/"
ENTRA_V2_ISSUER = f"https://login.microsoftonline.com/{ENTRA_TENANT_ID}/v2.0"

ENTRA_AUDIENCES = [ENTRA_AUDIENCE]
if ENTRA_AUDIENCE.startswith("api://"):
    ENTRA_AUDIENCES.append(ENTRA_AUDIENCE.removeprefix("api://"))
ENTRA_ISSUERS = [ENTRA_V1_ISSUER, ENTRA_V2_ISSUER]

ENTRA_JWKS_URI = (
    f"https://login.microsoftonline.com/{ENTRA_TENANT_ID}/discovery/v2.0/keys"
)

MS_GRAPH_TOKEN_URL = (
    f"https://login.microsoftonline.com/{ENTRA_TENANT_ID}/oauth2/v2.0/token"
)
MS_GRAPH_ME_URL = "https://graph.microsoft.com/v1.0/me"
MS_GRAPH_USER_SCOPE = "https://graph.microsoft.com/User.Read"
MS_GRAPH_PROFILE_FIELDS = ["id", "mail", "jobTitle", "department"]

# --- Azure Blob Storage ---

AZURE_STORAGE_ACCOUNT_URL = os.getenv("AZURE_STORAGE_ACCOUNT_URL", "")
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
AZURE_STORAGE_CONTAINER_NAME = os.getenv("AZURE_STORAGE_CONTAINER_NAME", "")
AZURE_UPLOAD_SAS_TTL_SECONDS = env_int("AZURE_UPLOAD_SAS_TTL_SECONDS", 15 * 60)
AZURE_DOWNLOAD_SAS_TTL_SECONDS = env_int("AZURE_DOWNLOAD_SAS_TTL_SECONDS", 5 * 60)
AZURE_MAX_UPLOAD_BYTES = env_int("AZURE_MAX_UPLOAD_BYTES", 100 * 1024 * 1024)

# --- Redis / Celery ---

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = env_int("REDIS_PORT", 6379)
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")
REDIS_SSL = os.getenv("REDIS_SSL", "false").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
}
REDIS_AUTH_PART = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""
REDIS_CACHE_SCHEME = "rediss" if REDIS_SSL else "redis"

CELERY_BROKER_DB = 0
CELERY_RESULT_DB = 1
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 960
CELERY_TASK_SOFT_TIME_LIMIT = 900
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "core.tasks.compute_visualization_task": {"queue": "visualization"},
    "core.tasks.compute_roi_task": {"queue": "roi"},
    "core.tasks.compute_node_testing_task": {"queue": "roi"},
    "core.tasks.compute_obm_task": {"queue": "roi"},
    "core.tasks.preprocess_case_task": {"queue": "preprocessing"},
}

# Partition edit-lock TTL (seconds). PartitionLockView acquires/renews with
# this window; a lock past its expiry is treated as free.
LOCK_TTL_SECONDS = int(os.getenv("LOCK_TTL_SECONDS", "600"))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_CACHE_SCHEME}://{REDIS_AUTH_PART}{REDIS_HOST}:{REDIS_PORT}/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SSL": REDIS_SSL,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 200,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            },
        },
        "TIMEOUT": 60,
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "security.auth.AppJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Avoid Django auth's AnonymousUser dependency; unauthenticated requests use
    # None until EntraIDAuthentication returns a real core.User.
    "UNAUTHENTICATED_USER": None,
}

# Allow the React frontend origin(s) to call the API from the browser.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-csrf-token"]

APP_JWT_ACCESS_TTL_SECONDS = 300
APP_JWT_REFRESH_TTL_SECONDS = 60 * 60 * 24 * 14

APP_JWT_ISSUER = "visualization-backend"
APP_JWT_AUDIENCE = "visualization-frontend"
APP_JWT_SIGNING_KEY = os.getenv("DJANGO_SECRET_KEY")

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "ENGINE": "django.db.backends.postgresql",
    }
}

USE_TZ = True
TIME_ZONE = "Asia/Kolkata"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
