# Generated by Django 5.2.15 on 2026-06-13 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "core"',
            reverse_sql='DROP SCHEMA IF EXISTS "core" CASCADE',
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entra_oid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("role", models.CharField(blank=True, max_length=32)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"core"."user"',
                "indexes": [
                    models.Index(fields=["entra_oid"], name="user_entra_o_bae555_idx"),
                    models.Index(fields=["email"], name="user_email_7bbb4c_idx"),
                ],
            },
        ),
    ]
