# Generated by Django 5.2.15 on 2026-06-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_case_caseuserassignment_dataset_partition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='product_type',
        ),
    ]
