# Generated by Django 5.2.4 on 2026-06-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_input_dataset_snapshot_workflowrun_datasets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, db_column='triggered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_workflow_runs', to='core.user'),
        ),
    ]
