# Generated by Django 5.2.4 on 2026-06-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_workflowrun_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to='core.user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to='core.user'),
        ),
        migrations.AlterField(
            model_name='caseuserassignment',
            name='case',
            field=models.ForeignKey(db_column='case', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.case'),
        ),
        migrations.AlterField(
            model_name='caseuserassignment',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to='core.user'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='case',
            field=models.ForeignKey(db_column='case', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='core.case'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasets', to='core.user'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='base_partition',
            field=models.ForeignKey(blank=True, db_column='base_partition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_partitions', to='core.partition'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='case',
            field=models.ForeignKey(db_column='case', on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='core.case'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partitions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_column='locked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_partitions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_partitions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='partition',
            field=models.ForeignKey(db_column='partition', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='core.partition'),
        ),
    ]
