# Generated by Django 5.2.4 on 2026-06-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_case_created_by_alter_case_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='step_status',
        ),
    ]
