# Generated by Django 5.2.4 on 2026-06-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_dataset_type_and_restore_selected_id_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "core"."uq_core_case_user_assign_active"',
                    reverse_sql=(
                        'CREATE UNIQUE INDEX "uq_core_case_user_assign_active" '
                        'ON "core"."assignments" ("case_id", "user_id") '
                        'WHERE NOT "is_deleted"'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='caseuserassignment',
                    name='uq_core_case_user_assign_active',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "core"."uq_core_partitions_active_name"',
                    reverse_sql=(
                        'CREATE UNIQUE INDEX "uq_core_partitions_active_name" '
                        'ON "core"."partitions" ("case", "name") '
                        'WHERE NOT "is_deleted"'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='partition',
                    name='uq_core_partitions_active_name',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "core"."idx_core_part_case"',
                    reverse_sql=(
                        'CREATE INDEX "idx_core_part_case" '
                        'ON "core"."partitions" ("case", "is_deleted")'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='partition',
                    name='idx_core_part_case',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='caseuserassignment',
            name='id',
        ),
        migrations.AddField(
            model_name='caseuserassignment',
            name='pk',
            field=models.CompositePrimaryKey('user', 'case', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "core"."assignments" '
                'ADD CONSTRAINT "assignments_pkey" PRIMARY KEY ("user_id", "case_id")'
            ),
            reverse_sql='ALTER TABLE "core"."assignments" DROP CONSTRAINT "assignments_pkey"',
        ),
        migrations.AlterField(
            model_name='partition',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='core.case'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='partition',
            field=models.ForeignKey(db_column='partition_id', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='core.partition'),
        ),
        migrations.AddIndex(
            model_name='partition',
            index=models.Index(fields=['case_id', 'is_deleted'], name='idx_core_part_case'),
        ),
        migrations.AddConstraint(
            model_name='partition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('case_id', 'name'), name='uq_core_partitions_active_name'),
        ),
    ]
