# Generated by Django 5.2.4 on 2026-06-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_caseuserassignment_uq_core_case_user_assign_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='partition',
            field=models.ForeignKey(db_column='partition_id', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.partition'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, db_column='triggered_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_workflows', to='core.user'),
        ),
    ]
