# Generated by Django 5.2.16 on 2026-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_consolidate_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='avg_roi',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
